package Demos;
/*
 * Chooser.java
 *
 * Created on 9 de marzo de 2007, 14:14
 */

import aima.search.eightpuzzle.EightPuzzleJFrame;
import IA.probIA15.ProbIA15JFrame;
import IA.probPathFinder.ProbPathFinderJFrame;
import IA.probAntenas.ProbAntenasJFrame;
import IA.Marenostrum.MarenostrumJFrame;
import IA.Centrals.CentralsJFrame;
import IA.Connectat.ConnectatJFrame;
import IA.Electrica.ElectricaJFrame;
import IA.Electricidad.DistribucionGrafico;
import IA.Gasolineras.GasolinerasJFrame;
import IA.PathFinderDemo.ProbPathFinderDemoJFrame;
import IA.petroli.PetroliWindow;
import IA.TSP2.ProbTSPJFrame;

/**
 *
 * @author  bejar
 */
public class Chooser extends javax.swing.JFrame {

    /** Creates new form Chooser */
    public Chooser() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        OchoPuzzle = new javax.swing.JButton();
        ProbIA15 = new javax.swing.JButton();
        PathFinder = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Antenas = new javax.swing.JButton();
        Marenostrum = new javax.swing.JButton();
        Centrals = new javax.swing.JButton();
        Connectat = new javax.swing.JButton();
        Electrica = new javax.swing.JButton();
        Electricidad = new javax.swing.JButton();
        TSP = new javax.swing.JButton();
        Petroli = new javax.swing.JButton();
        Gasolineras = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ejemplos de problemas de Búsqueda");

        OchoPuzzle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OchoPuzzleMouseClicked(evt);
            }
        });

        ProbIA15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProbIA15MouseClicked(evt);
            }
        });

        PathFinder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PathFinderMouseClicked(evt);
            }
        });

        jLabel2.setText("Ocho Puzzle");

        jLabel3.setText("Problema 15");

        jLabel4.setText("Path Finder");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(ProbIA15, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(PathFinder, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(OchoPuzzle, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 139, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3)
                    .add(jLabel4))
                .addContainerGap(259, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(32, 32, 32)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(OchoPuzzle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(ProbIA15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(17, 17, 17)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(PathFinder, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Búsqueda Heurística", jPanel1);

        Antenas.setText("Antenas");
        Antenas.setAlignmentY(0.0F);
        Antenas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AntenasMouseClicked(evt);
            }
        });

        Marenostrum.setText("Marenostrum");
        Marenostrum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MarenostrumMouseClicked(evt);
            }
        });

        Centrals.setText("Centrals");
        Centrals.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CentralsMouseClicked(evt);
            }
        });

        Connectat.setText("Connectat");
        Connectat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConnectatMouseClicked(evt);
            }
        });

        Electrica.setText("Electrica");
        Electrica.setAlignmentY(0.0F);
        Electrica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ElectricaMouseClicked(evt);
            }
        });

        Electricidad.setText("Electricidad");
        Electricidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ElectricidadMouseClicked(evt);
            }
        });

        TSP.setText("TSP");
        TSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TSPActionPerformed(evt);
            }
        });

        Petroli.setText("Petroli");
        Petroli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PetroliActionPerformed(evt);
            }
        });

        Gasolineras.setText("Gasolineras");
        Gasolineras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GasolinerasMouseClicked(evt);
            }
        });
        Gasolineras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GasolinerasActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(Antenas, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .add(Marenostrum, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .add(Centrals, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .add(TSP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                .add(18, 18, 18)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(Electricidad, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .add(Connectat, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, Petroli, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .add(Electrica, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(Gasolineras, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .add(54, 54, 54))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(2, 2, 2)
                        .add(TSP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(Connectat, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, Short.MAX_VALUE)
                        .add(Gasolineras, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, Short.MAX_VALUE)))
                .add(10, 10, 10)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(Antenas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, Short.MAX_VALUE)
                    .add(Electrica, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, Short.MAX_VALUE))
                .add(15, 15, 15)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(Marenostrum, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, Short.MAX_VALUE)
                    .add(Electricidad, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, Short.MAX_VALUE))
                .add(14, 14, 14)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(1, 1, 1)
                        .add(Centrals, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(Petroli, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, Short.MAX_VALUE))
                .add(19, 19, 19))
        );

        jTabbedPane1.addTab("Búsqueda Local", jPanel2);

        jButton1.setText("Path Finder 2");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(26, 26, 26)
                .add(jButton1)
                .addContainerGap(349, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jButton1)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Otros", jPanel3);

        jMenu1.setText("Menu");

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jMenu1.add(Salir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(85, 85, 85)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jSeparator1)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 172, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 206, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void TSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TSPActionPerformed
// TODO add your handling code here:
        ProbTSPJFrame el = new ProbTSPJFrame();

        el.setVisible(true);
    }//GEN-LAST:event_TSPActionPerformed

    private void ElectricidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ElectricidadMouseClicked
// TODO add your handling code here:
        DistribucionGrafico el = new DistribucionGrafico();

        el.setVisible(true);
    }//GEN-LAST:event_ElectricidadMouseClicked

    private void ElectricaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ElectricaMouseClicked
// TODO add your handling code here:
        ElectricaJFrame el = new ElectricaJFrame();

        el.setVisible(true);
    }//GEN-LAST:event_ElectricaMouseClicked

    private void ConnectatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConnectatMouseClicked
// TODO add your handling code here:
        ConnectatJFrame conn = new ConnectatJFrame();

        conn.setVisible(true);
    }//GEN-LAST:event_ConnectatMouseClicked

    private void CentralsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CentralsMouseClicked
// TODO add your handling code here:
        CentralsJFrame cen = new CentralsJFrame();

        cen.setVisible(true);
    }//GEN-LAST:event_CentralsMouseClicked

    private void MarenostrumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MarenostrumMouseClicked
// TODO add your handling code here:
        MarenostrumJFrame Mar = new MarenostrumJFrame();

        Mar.setVisible(true);
    }//GEN-LAST:event_MarenostrumMouseClicked

    private void AntenasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AntenasMouseClicked
// TODO add your handling code here:
        ProbAntenasJFrame Ant = new ProbAntenasJFrame();

        Ant.setVisible(true);
    }//GEN-LAST:event_AntenasMouseClicked

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
// TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void PathFinderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PathFinderMouseClicked
// TODO add your handling code here:
        ProbPathFinderJFrame PF = new ProbPathFinderJFrame();

        PF.setVisible(true);
    }//GEN-LAST:event_PathFinderMouseClicked

    private void ProbIA15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProbIA15MouseClicked
// TODO add your handling code here:
        ProbIA15JFrame PIA15 = new ProbIA15JFrame();

        PIA15.setVisible(true);
    }//GEN-LAST:event_ProbIA15MouseClicked

    private void OchoPuzzleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OchoPuzzleMouseClicked
// TODO add your handling code here:       
        EightPuzzleJFrame iOchoPuzzle = new EightPuzzleJFrame();

        iOchoPuzzle.setVisible(true);
       
    }//GEN-LAST:event_OchoPuzzleMouseClicked

    private void PetroliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PetroliActionPerformed
        PetroliWindow finestra = new PetroliWindow();
        finestra.setVisible(true);

}//GEN-LAST:event_PetroliActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

                ProbPathFinderDemoJFrame PF = new ProbPathFinderDemoJFrame();
                PF.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

private void GasolinerasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GasolinerasMouseClicked
// TODO add your handling code here:
}//GEN-LAST:event_GasolinerasMouseClicked

private void GasolinerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GasolinerasActionPerformed
                GasolinerasJFrame PF = new GasolinerasJFrame();
                PF.setVisible(true);

}//GEN-LAST:event_GasolinerasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Chooser().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Antenas;
    private javax.swing.JButton Centrals;
    private javax.swing.JButton Connectat;
    private javax.swing.JButton Electrica;
    private javax.swing.JButton Electricidad;
    private javax.swing.JButton Gasolineras;
    private javax.swing.JButton Marenostrum;
    private javax.swing.JButton OchoPuzzle;
    private javax.swing.JButton PathFinder;
    private javax.swing.JButton Petroli;
    private javax.swing.JButton ProbIA15;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JButton TSP;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
