package IA.Electrica;

import java.awt.*;
import java.awt.geom.*;
import javax.swing.*;
import java.util.Date;
import java.util.Calendar;
import java.io.*;

import java.util.Iterator;
import java.util.List;
import java.util.Properties;
import java.util.Vector;

//import IA.centrales.CentralesGoalTest;
//import IA.centrales.CentralesSuccessorFunction;
//import IA.centrales.CentralesHeuristicFunction;
//import IA.centrales.CentralesBoard;

import aima.search.framework.Successor;
import aima.search.framework.GraphSearch;
import aima.search.framework.Problem;
import aima.search.framework.Search;
import aima.search.framework.SearchAgent;
import aima.search.framework.TreeSearch;
import aima.search.informed.SimulatedAnnealingSearch;
import aima.search.informed.HillClimbingSearch;

/**
 * 
 * @author javier
 * setPlano
 */
public class ElectricaJFrame extends javax.swing.JFrame {

    private Electrica e;
    private int alg = 1;
    private int heur = 1;
    private int np = 3;
    private int nc = 3;
    private int ncomp = 2;
    private int op = 3;
    private int solinivar = 1;
    //	simulated anealing parametres(2000,100,5,0.001);
    //2000,1000,3,0.001
    //2000,1000,2,0.001--salta pero mateix val heuristic
    private int steps = 10000;
    private int k = 500;
    private int lamb = 5;
    private float limit = (float) 0.011;

    /** Creates new form CentralesJFrame */
    public ElectricaJFrame() {
        initComponents();

        e = new Electrica(nc, ncomp);
        np = e.obteNpaquets();
        drawPanel1.setPlano(np, nc, e.getPlano());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {// GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();

        numconsumidors = new javax.swing.JLabel();
        ncons = new javax.swing.JTextField();
        numpaquets = new javax.swing.JLabel();
        npaqs = new javax.swing.JTextField();

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        HC = new javax.swing.JRadioButton();
        SA = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        heur1 = new javax.swing.JRadioButton();
        heur2 = new javax.swing.JRadioButton();
        heur3 = new javax.swing.JRadioButton();
        heur4 = new javax.swing.JRadioButton();
        heur5 = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tiempo = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        reiniciar = new javax.swing.JButton();
        solini = new javax.swing.JButton();
        ejecutar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        instrum = new javax.swing.JTextArea();
        // val heuristic
        jLabel5 = new javax.swing.JLabel();
        valHeur = new javax.swing.JTextField();
        // operadors
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        op1 = new javax.swing.JRadioButton();
        op2 = new javax.swing.JRadioButton();
        op3 = new javax.swing.JRadioButton();
        buttonGroup3 = new javax.swing.ButtonGroup();

        drawPanel1 = new IA.Electrica.ElectricaPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Salir = new javax.swing.JMenuItem();

//		 sol ini
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        s1 = new javax.swing.JRadioButton();
        s2 = new javax.swing.JRadioButton();
        s3 = new javax.swing.JRadioButton();
        s4 = new javax.swing.JRadioButton();
        buttonGroup4 = new javax.swing.ButtonGroup();

        // finestra gran
        getContentPane().setLayout(new java.awt.GridBagLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Demanda Electrica");

        // panel de num paquest num consumidors

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        numpaquets.setText("Num Companyies:");
        jPanel3.add(numpaquets);

        npaqs.setColumns(4);
        npaqs.setText(ncomp + "");
        jPanel3.add(npaqs);

        numconsumidors.setText("Num Consumidors:");
        jPanel3.add(numconsumidors);

        ncons.setColumns(3);
        ncons.setText(nc + "");
        jPanel3.add(ncons);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel3, gridBagConstraints);

        // panel 2 el panel de Algorismes
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel4.setText("Algorisme: ");
        jPanel2.add(jLabel4, new java.awt.GridBagConstraints());

        HC.setSelected(true);
        HC.setText("Hill Climbing");
        buttonGroup1.add(HC);
        HC.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HCActionPerformed(evt);
            }
        });

        jPanel2.add(HC, new java.awt.GridBagConstraints());

        SA.setText("S.Annealing");
        buttonGroup1.add(SA);
        SA.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAActionPerformed(evt);
            }
        });

        jPanel2.add(SA, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 6;
        getContentPane().add(jPanel2, gridBagConstraints);

        // panel Heuristics
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel3.setText("Heuristiques: ");
        jPanel5.add(jLabel3, new java.awt.GridBagConstraints());

        heur1.setSelected(true);
        buttonGroup2.add(heur1);
        heur1.setLabel("Heuristic 1");
        heur1.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heur1ActionPerformed(evt);
            }
        });

        jPanel5.add(heur1, new java.awt.GridBagConstraints());

        buttonGroup2.add(heur2);
        heur2.setLabel("Heuristic 2");
        heur2.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heur2ActionPerformed(evt);
            }
        });

        jPanel5.add(heur2, new java.awt.GridBagConstraints());

        buttonGroup2.add(heur3);
        heur3.setLabel("Heuristic 3");
        heur3.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heur3ActionPerformed(evt);
            }
        });

        jPanel5.add(heur3, new java.awt.GridBagConstraints());

        buttonGroup2.add(heur4);
        heur4.setLabel("Heuristic 4");
        heur4.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heur4ActionPerformed(evt);
            }
        });
//tiempo
        jPanel5.add(heur4, new java.awt.GridBagConstraints());

        buttonGroup2.add(heur5);
        heur5.setLabel("Heuristico 5");
        heur5.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heur5ActionPerformed(evt);
            }
        });

        //jPanel5.add(heur5, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jPanel5, gridBagConstraints);

        // panel temps i val heuristic
        jPanel6.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Temps: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(1, 27, 0, 0);
        jPanel6.add(jLabel1, gridBagConstraints);

        tiempo.setColumns(10);
        tiempo.setEditable(false);
        jPanel6.add(tiempo, new java.awt.GridBagConstraints());

        jLabel5.setText("Valor Heuristic: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(1, 27, 0, 0);
        jPanel6.add(jLabel5, gridBagConstraints);

        valHeur.setColumns(10);
        valHeur.setEditable(false);
        jPanel6.add(valHeur, new java.awt.GridBagConstraints());

        // panel operadors<
		/*
         * jPanel8 = new javax.swing.JPanel(); jLabel6 = new
         * javax.swing.JLabel(); op1 = new javax.swing.JRadioButton() ; op2 =
         * new javax.swing.JRadioButton(); op3 = n
         */
        jPanel8.setLayout(new java.awt.GridBagLayout());

        jLabel6.setText("Operadors: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(1, 27, 0, 0);
        jPanel8.add(jLabel6, new java.awt.GridBagConstraints());

        op1.setSelected(false);
        buttonGroup3.add(op1);
        op1.setLabel("afegir/treure");
        op1.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op1ActionPerformed(evt);
            }
        });

        jPanel8.add(op1, new java.awt.GridBagConstraints());

        op2.setSelected(false);
        buttonGroup3.add(op2);
        op2.setLabel("interc + af/tre");
        op2.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op2ActionPerformed(evt);
            }
        });

        jPanel8.add(op2, new java.awt.GridBagConstraints());

        op3.setSelected(true);
        buttonGroup3.add(op3);
        op3.setLabel("creu + af/treure");
        op3.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op3ActionPerformed(evt);
            }
        });

        jPanel8.add(op3, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jPanel8, gridBagConstraints);

        //panel sol ini

        jPanel9.setLayout(new java.awt.GridBagLayout());

        jLabel7.setText("Solucions inicial: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(1, 27, 0, 0);
        jPanel9.add(jLabel7, new java.awt.GridBagConstraints());

        s1.setSelected(false);
        buttonGroup4.add(s1);
        s1.setLabel("buida");
        s1.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1ActionPerformed(evt);
            }
        });

        jPanel9.add(s1, new java.awt.GridBagConstraints());

        s2.setSelected(false);
        buttonGroup4.add(s2);
        s2.setLabel("aleatoria");
        s2.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s2ActionPerformed(evt);
            }
        });

        jPanel9.add(s2, new java.awt.GridBagConstraints());

        s3.setSelected(true);
        buttonGroup4.add(s3);
        s3.setLabel("vora� pitjor");
        s3.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s3ActionPerformed(evt);
            }
        });

        jPanel9.add(s3, new java.awt.GridBagConstraints());
        s4.setSelected(true);
        buttonGroup4.add(s4);
        s4.setLabel("vora� millor");
        s4.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s4ActionPerformed(evt);
            }
        });

        jPanel9.add(s4, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jPanel9, gridBagConstraints);

        // panel botons actualitzar i exectuar
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jPanel6, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(200, 35));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 35));
        reiniciar.setText("Actualitzar parametres");
        reiniciar.setToolTipText("Reiniciar el mapa");
        reiniciar.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mousePressed(java.awt.event.MouseEvent evt) {
                reiniciarMousePressed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel1.add(reiniciar, gridBagConstraints);



        ejecutar.setText("Executar");
        ejecutar.setToolTipText("Ejecutar el algoritmo seleccionado");
        ejecutar.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mousePressed(java.awt.event.MouseEvent evt) {
                ejecutarMousePressed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel1.add(ejecutar, gridBagConstraints);

        solini.setText("Solucio inicial");
        solini.setToolTipText("mostra sol ini");
        solini.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mousePressed(java.awt.event.MouseEvent evt) {
                soliniMousePressed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanel1.add(solini, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel1, gridBagConstraints);

        // panel amb matriu i instrumentacio
        jPanel7.setLayout(new java.awt.GridBagLayout());

        jPanel7.setPreferredSize(new java.awt.Dimension(600, 400));
        // afegir barra despla�ament al textAreat instrum??

        instrum.setColumns(10);
        instrum.setEditable(false);
        instrum.setLineWrap(true);
        instrum.setRows(10);
        instrum.setPreferredSize(new java.awt.Dimension(180, 300));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;

        scrollpane = new javax.swing.JScrollPane(instrum);
        jPanel7.add(scrollpane, gridBagConstraints);

        drawPanel1.setPreferredSize(new java.awt.Dimension(400, 400));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel7.add(drawPanel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        getContentPane().add(jPanel7, gridBagConstraints);

        jMenu1.setText("Menu");
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        jMenu1.add(Salir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// GEN-END:initComponents

    private void heur5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_heur3ActionPerformed
        // TODO add your handling code here:
        heur = 5;
    }

    private void heur4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_heur3ActionPerformed
        // TODO add your handling code here:
        heur = 4;
    }// GEN-LAST:event_heur3ActionPerformed

    private void heur3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_heur3ActionPerformed
        // TODO add your handling code here:
        heur = 3;
    }// GEN-LAST:event_heur3ActionPerformed

    private void heur1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_heur1ActionPerformed
        // TODO add your handling code here:
        heur = 1;
    }// GEN-LAST:event_heur1ActionPerformed

    private void heur2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_heur2ActionPerformed
        // TODO add your handling code here:
        heur = 2;
    }// GEN-LAST:event_heur2ActionPerformed

    private void op1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_heur1ActionPerformed
        // TODO add your handling code here:
        op = 1;
    }// GEN-LAST:event_heur1ActionPerformed

    private void op2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_heur1ActionPerformed
        // TODO add your handling code here:
        op = 2;
    }// GEN-LAST:event_heur1ActionPerformed

    private void op3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_heur1ActionPerformed
        // TODO add your handling code here:
        op = 3;
    }// GEN-LAST:event_heur1ActionPerformed

    private void s1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_heur1ActionPerformed
        // TODO add your handling code here:
        solinivar = 1;
    }// GEN-LAST:event_heur1ActionPerformed

    private void s2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_heur1ActionPerformed
        // TODO add your handling code here:
        solinivar = 2;
    }// GEN-LAST:event_heur1ActionPerformed

    private void s3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_heur1ActionPerformed
        // TODO add your handling code here:
        solinivar = 3;
    }// GEN-LAST:event_heur1ActionPerformed

    private void s4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_heur1ActionPerformed
        // TODO add your handling code here:
        solinivar = 4;
    }// GEN-LAST:event_heur1ActionPerformed

    private void SAActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SAActionPerformed
        // TODO add your handling code here:
        alg = 2;
    }// GEN-LAST:event_SAActionPerformed

    private void HCActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_HCActionPerformed
        // TODO add your handling code here:
        alg = 1;
    }// GEN-LAST:event_HCActionPerformed

    private void reiniciarMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_reiniciarMousePressed
        // TODO add your handling code here:
        String s;
        s = ncons.getText();
        nc = Integer.parseInt(s);

        s = npaqs.getText();
        ncomp = Integer.parseInt(s);

        e = new Electrica(nc, ncomp);
        np = e.obteNpaquets();
        // p.prtMatrix(p.getPlano(), nc+nr );

        drawPanel1.setPlano(np, nc, e.getPlano());

    }// GEN-LAST:event_reiniciarMousePressed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }// GEN-LAST:event_SalirActionPerformed

    private void ejecutarMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_ejecutarMousePressed
        // TODO add your handling code here:


        Search search = null;
        Problem problem = null;

        if (solinivar == 1) {
            e.solucioInicial1();
        } //buida
        else if (solinivar == 2) {
            e.solucioInicial2();
        } //tal cual aleatoria
        else if (solinivar == 3) {
            //System.out.println("solucio inicial vora� pitjor");
            if (heur == 1) {
                e.solucioInicial3();
            }
            if (heur == 2) {
                e.solucioInicial4p();
            }
        } else if (solinivar == 4) {
            //System.out.println("solucio inicial vora�  millor");
            if (heur == 1) {
                e.solucioInicial4();
            }
            if (heur == 2) {
                e.solucioInicial3p();
            }
        }

        int heuristiini = -e.obteValHeuristic(heur);
        System.out.println("SOL INI ACABAT");
        //if per el heuristic!!!
        if (op == 1) {
            if (heur == 1) {
                problem = new Problem(e, new ElectricaSuccessorFunction(),
                        new ElectricaGoalTest(), new ElectricaHeuristicFunction());
            } else if (heur == 2) {
                problem = new Problem(e, new ElectricaSuccessorFunction(),
                        new ElectricaGoalTest(), new ElectricaHeuristicFunction2());
            } else if (heur == 3) {
                problem = new Problem(e, new ElectricaSuccessorFunction(),
                        new ElectricaGoalTest(), new ElectricaHeuristicFunction3());
            } else if (heur == 4) {
                problem = new Problem(e, new ElectricaSuccessorFunction(),
                        new ElectricaGoalTest(), new ElectricaHeuristicFunction4());
            } else if (heur == 5) {
                problem = new Problem(e, new ElectricaSuccessorFunction(),
                        new ElectricaGoalTest(), new ElectricaHeuristicFunction5());
            }
        } else if (op == 2) {
            if (heur == 1) {
                problem = new Problem(e, new ElectricaSuccessorFunction3(),
                        new ElectricaGoalTest(), new ElectricaHeuristicFunction());
            } else if (heur == 2) {
                problem = new Problem(e, new ElectricaSuccessorFunction3(),
                        new ElectricaGoalTest(), new ElectricaHeuristicFunction2());
            } else if (heur == 3) {
                problem = new Problem(e, new ElectricaSuccessorFunction3(),
                        new ElectricaGoalTest(), new ElectricaHeuristicFunction3());
            } else if (heur == 4) {
                problem = new Problem(e, new ElectricaSuccessorFunction3(),
                        new ElectricaGoalTest(), new ElectricaHeuristicFunction4());
            } else if (heur == 5) {
                problem = new Problem(e, new ElectricaSuccessorFunction3(),
                        new ElectricaGoalTest(), new ElectricaHeuristicFunction5());
            }
        } else if (op == 3) {
            if (heur == 1) {
                problem = new Problem(e, new ElectricaSuccessorFunction4(),
                        new ElectricaGoalTest(), new ElectricaHeuristicFunction());
            } else if (heur == 2) {
                problem = new Problem(e, new ElectricaSuccessorFunction4(),
                        new ElectricaGoalTest(), new ElectricaHeuristicFunction2());
            } else if (heur == 3) {
                problem = new Problem(e, new ElectricaSuccessorFunction4(),
                        new ElectricaGoalTest(), new ElectricaHeuristicFunction3());
            } else if (heur == 4) {
                problem = new Problem(e, new ElectricaSuccessorFunction4(),
                        new ElectricaGoalTest(), new ElectricaHeuristicFunction4());
            } else if (heur == 4) {
                problem = new Problem(e, new ElectricaSuccessorFunction4(),
                        new ElectricaGoalTest(), new ElectricaHeuristicFunction5());
            }
        }
        if (alg == 1) {
            search = new HillClimbingSearch();
        } else {
            search = new SimulatedAnnealingSearch(steps, k, lamb, limit);
        }
        try {
            Date d1, d2;
            Calendar a, b;
            System.out.println("Sol ini:");
            e.EscriuEstat();
            System.out.println("b:" + e.obteBenefici() + " p:" + e.obtePagament() + " fm:" + e.obteFactorMig() + " qNoAsig:" + e.obteQnoAssignada() + " qNoCons:" + e.obteQnoConsumida());

            d1 = new Date();
            SearchAgent agent = new SearchAgent(problem, search);
            d2 = new Date();

            a = Calendar.getInstance();
            b = Calendar.getInstance();
            a.setTime(d1);
            b.setTime(d2);

            long m = b.getTimeInMillis() - a.getTimeInMillis();

            tiempo.setText(m + " ms");
            Electrica ef = null;

            if (search instanceof HillClimbingSearch) {
                ef = (Electrica) ((HillClimbingSearch)search).getLastSearchState();
            } else {
                ef = (Electrica) ((SimulatedAnnealingSearch)search).getLastSearchState();
            }

            System.out.println("Sol final:");
            ef.EscriuEstat();
            if (heur == 1) {
                valHeur.setText(Integer.toString(-ef.obteValHeuristic(1)));
            } else if (heur == 2) {
                valHeur.setText(Integer.toString(-ef.obteValHeuristic(2)));
            } else if (heur == 3) {
                valHeur.setText(Integer.toString(-ef.obteValHeuristic(3)));
            } else if (heur == 4) {
                valHeur.setText(Integer.toString(-ef.obteValHeuristic(4)));
            } else if (heur == 4) {
                valHeur.setText(Integer.toString(-ef.obteValHeuristic(5)));
            }
            System.out.println("b:" + e.obteBenefici() + " p:" + e.obtePagament() + " fm:" + e.obteFactorMig() + " qNoAsig:" + e.obteQnoAssignada() + " qNoCons:" + e.obteQnoConsumida());

            System.out.println("num passos= " + ef.NombreDePassos());
            System.out.println("b:" + ef.obteBenefici() + " p:" + ef.obtePagament() + " fm:" + ef.obteFactorMig() + " qNoAsig:" + ef.obteQnoAssignada() + " qNoCons:" + ef.obteQnoConsumida());
            drawPanel1.setPlano(np, nc, ef.getPlano());


            //printInstrumentation(agent.getInstrumentation());
            //printActions(agent.getActions());

            instrum.append("heuristic ini=" + heuristiini + "\n");
            instrum.append("heuristic final=" + ef.obteValHeuristic(heur) + "\n");


        } catch (Exception e) {
            e.printStackTrace();
        }

    }// GEN-LAST:event_ejecutarMousePressed

    private void soliniMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_ejecutarMousePressed
        // TODO add your handling code here:


        if (solinivar == 1) {
            e.solucioInicial1();
        } //buida
        else if (solinivar == 2) {
            e.solucioInicial2();
        } //tal cual aleatoria
        else if (solinivar == 3) {
            //System.out.println("solucio inicial vora� pitjor");
            if (heur == 1) {
                e.solucioInicial3();
            }
            if (heur == 2) {
                e.solucioInicial3p();
            }
        } else if (solinivar == 4) {
            //System.out.println("solucio inicial vora�  millor");
            if (heur == 1) {
                e.solucioInicial4();
            }
            if (heur == 2) {
                e.solucioInicial4p();
            }
        }
        int heuristiini = -e.obteValHeuristic(heur);
        System.out.println("SOL INI ACABAT");
        drawPanel1.setPlano(np, nc, e.getPlano());
        e.EscriuEstat();
        if (heur == 1) {
            valHeur.setText(Integer.toString(-e.obteValHeuristic(1)));
        } else if (heur == 2) {
            valHeur.setText(Integer.toString(-e.obteValHeuristic(2)));
        } else if (heur == 3) {
            valHeur.setText(Integer.toString(-e.obteValHeuristic(3)));
        } else if (heur == 4) {
            valHeur.setText(Integer.toString(-e.obteValHeuristic(4)));
        }



    }// GEN-LAST:event_ejecutarMousePressed

    private void printInstrumentation(Properties properties) {

        Iterator keys = properties.keySet().iterator();
        instrum.setText("");
        while (keys.hasNext()) {
            String key = (String) keys.next();
            String property = properties.getProperty(key);
            instrum.append(key + " : " + property + "\n");
            // System.out.println(key + " : " + property);
        }

    }

    private static void printActions(List actions) {
        System.out.println("tamany llista actions:" + actions.size());
        for (int i = 0; i < actions.size(); i++) {
            String action = (String) actions.get(i);
            System.out.println(action);
        }
    }

    /**
     * @param args
     *            the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ElectricaJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton HC;
    private javax.swing.JRadioButton SA;
    private javax.swing.JMenuItem Salir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private IA.Electrica.ElectricaPanel drawPanel1;
    private javax.swing.JButton ejecutar;
    private javax.swing.JRadioButton heur1;
    private javax.swing.JRadioButton heur2;
    private javax.swing.JRadioButton heur3;
    private javax.swing.JRadioButton heur4;
    private javax.swing.JRadioButton heur5;
    private javax.swing.JTextArea instrum;
    private javax.swing.JScrollPane scrollpane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // private javax.swing.JLabel jLabel6;
    // private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    // private javax.swing.JTextField maxrepT;
    // private javax.swing.JTextField ncent;
    private javax.swing.JTextField ncons;
    // private javax.swing.JTextField nreps;
    private javax.swing.JTextField npaqs;
    // private javax.swing.JLabel numrepetidores;
    private javax.swing.JLabel numpaquets;
    // private javax.swing.JLabel nuncentrales;
    private javax.swing.JLabel numconsumidors;
    private javax.swing.JButton reiniciar;
    private javax.swing.JButton solini;
    // private javax.swing.JLabel size;
    // private javax.swing.JComboBox sizes;
    private javax.swing.JTextField tiempo;
    // End of variables declaration//GEN-END:variables
    // val heuristic
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField valHeur;
    // operadors
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton op1;
    private javax.swing.JRadioButton op2;
    private javax.swing.JRadioButton op3;
//	 sol ini
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton s1;
    private javax.swing.JRadioButton s2;
    private javax.swing.JRadioButton s3;
    private javax.swing.JRadioButton s4;
}
